### ISSUE TITLE
Sync animation with actual attack

### ISSUE THREAD

**Issue by trudeaua** [olejarza/VACATe#74]
- Right now there is no syncing between an attack animation and the actual attack, especially noticeable when spamming an attack button
- We need to find a way to sync the two so it looks nice and makes sense

**Comment by camvr** [comment]
This is currently controlled by two values in the combat controllers: The attack "cooldown", and the damage delay. The attack cooldowns were set almost randomly by me before we had the animations in place, however they should be set to at least the length of the attack animation otherwise we will get the issue of attack animations not triggering but damage being dealt. The point at which damage is dealt is controlled by the damage delay, which allows us to sync up when for instance the sword hits the enemy and then damage is done. For the next implementation I am hoping to have implemented this "StatSheet" idea I have which would allow us to tweak these values much easier

**Comment by trudeaua** [comment]
@camvr I messed around with each class' combat controller and animation controller today, as well as `PlayerCombatController.cs` and `EntityCombatController.cs` to sync up the attacks with the animations. 

The biggest benefit of what I did today is that animations are no longer interrupted by other attacks, and players can spam the attack button now because the attack + animation are synced up. I played around with each class and spammed the primary and secondary attack buttons. Everything pretty much works and it's way better than what we had for the demo. 

Check out the changes in `animation-dev-new` and lemme know what you think. If you think your StatSheet idea will solve this better than what I did then I can undo my changes :)

**Comment by camvr** [comment]
@trudeaua Sorry to get back to this a bit late, but I would say keep your changes in since ultimately the StatSheet would simply migrate the values you tweaked into an object that is simply much easier to tweak and mess with from the Unity Editor's inspector. Glad you managed to find some suitable time delays!

**Comment by trudeaua** [comment]
Closing this issue for now since the syncing is pretty much perfect.
